version: '3.4'

services:
  placeholder.api:
    environment:
        - ConnectionString_DataSource=db, 1433
        - ConnectionString_InitialCatalog=master
        - ConnectionString_UserId=sa
        - ConnectionString_Password=A&VeryComplex123Password;
    image: ${DOCKER_REGISTRY-}placeholderapi
    build:
      context: .
      dockerfile: src/PlaceHolder.API/Dockerfile
    depends_on:
        - db
        - kafka

  db:
    container_name: "SqlServer2022"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
    - "1433:1433"
    environment:
        SA_PASSWORD: "A&VeryComplex123Password"
        ACCEPT_EULA: "Y"
 
  kafka:
      container_name: "Kafka"
      ports:
          - '2181:2181' #ZooKeeper
          - '3030:3030' #Web Server
          - '8081:8081' #Schema Registry
          - '8082:8082' #Kafka REST Proxy
          - '8083:8083' #Kafka Connect Distributed
          - '9092:9092' #Kafka Broker
      environment:
          - ADV_HOST=kafka
      image: landoop/fast-data-dev