version: '3.4'

services:
  placeholder.api:
    image: ${DOCKER_REGISTRY-}placeholderapi
    build:
      context: .
      dockerfile: src/PlaceHolder.API/Dockerfile
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
    - "1433:1433"
    environment:
        SA_PASSWORD: "A&VeryComplex123Password"
        ACCEPT_EULA: "Y"